### PR TITLE
Replaced PDB files by those used to calibrate NACCESS relative accessibilities

### PR DESCRIPTION
**Pull request by JoaoRodrigues**

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
The `configure.ac` change was because in my BASH (WSL) configure was breaking because of weird characters, which I traced back to a few newline characters in `configure.ac`.

**Comment by mittinatten** [comment]
Great! Will just have to some fixes to accomodate these in the test suite, there are some tricks in the CLI tests that depene explicitly on the details on the specific PDB files. Do we have/need an ok from Hubbard & Thornton to include these?

**Comment by JoaoRodrigues** [comment]
Perfect! I will ask, but I guess it's OK (too late too to go back!)

**Comment by JoaoRodrigues** [comment]
All good by the NACCESS author.

**Pull request merged**
